# Generated by Django 3.1.7 on 2021-06-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210606_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodadd',
            name='food_photolink',
            field=models.CharField(default='link will be here', max_length=200),
        ),
        migrations.AlterField(
            model_name='foodadd',
            name='food_name',
            field=models.CharField(max_length=150),
        ),
    ]
